---
- name: Download and Deploy WAR File
  hosts: app
  become: yes  # You may need to elevate privileges to copy files to Tomcat's webapps directory

  tasks:
    - name: Copy the WAR file from Jenkins workspace to Ansible control machine
      synchronize:
        src: "/var/lib/jenkins/workspace/dev/webapp/target/webapp.war"  # Update this path to the actual Jenkins workspace path
        dest: "/tmp/webapp.war"
        mode: pull
        # rsync_opts: ["-avz", "--progress"]  # Optional - adjust rsync options

    - name: Copy the WAR file to the Tomcat webapps directory on the target machine
      copy:
        src: /tmp/webapp.war
        dest: /path/to/tomcat/webapps/webapp.war
        owner: tomcat  # Replace with the appropriate user that Tomcat runs as
        group: tomcat  # Replace with the appropriate group for Tomcat
        mode: 0777  # Adjust the permissions as needed

    - name: Restart Tomcat to deploy the WAR file
      systemd:
        name: tomcat  # Replace with the name of your Tomcat systemd service
        state: restarted
